name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Trigger deployment on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.FARHAN_SECRET }}

    - name: Deploy to 3.107.88.155
      run: |
        ssh -i ahan.pem -o StrictHostKeyChecking=no ec2-user@3.107.88.155 << 'EOF'
          # Masuk ke direktori dan perbaiki izin
          cd /var/www/html/cc-uts
          git config --global --add safe.directory /var/www/html/cc-uts
          sudo chown -R ec2-user:ec2-user /var/www/html/cc-uts
          sudo chmod -R 755 /var/www/html/cc-uts

          # Menyimpan perubahan lokal jika ada
          git stash || true  # Jika tidak ada perubahan, git stash tidak akan error

          # Menarik pembaruan dari repository
          git pull origin main

          # Mengembalikan perubahan lokal yang disimpan
          git stash pop || true

          # Restart layanan HTTPD
          sudo systemctl restart httpd

          # Kembali ke direktori home dan copy file app.js
          cd ~
          scp -i ahan.pem -o StrictHostKeyChecking=no /var/www/html/cc-uts/app.js ec2-user@10.0.2.224:/home/ec2-user/cc-uts
          
          # SSH ke server tujuan dan restart app.js menggunakan PM2
          ssh -i ahan.pem -o StrictHostKeyChecking=no ec2-user@10.0.2.224\
            cd /home/ec2-user/cc-uts
            pm2 restart app.js

        EOF
